### ISSUE TITLE
Building and Managing Data Science Pipelines with Kedro

### ISSUE THREAD

**Issue by kennethleungty** [kedro-org/kedro-community#99]
Hi there,

Sharing an article I wrote on using Kedro to build and manage an isolation forest anomaly detection pipeline: https://neptune.ai/blog/data-science-pipelines-with-kedro  (Link to GitHub repo: https://github.com/kennethleungty/Anomaly-Detection-Pipeline-Kedro)

Happy to have this included in this list of Kedro projects!

**Comment by MerelTheisenQB** [comment]
Hi @kennethleungty, apologies for the ridiculously late response 🤦‍♀️ This completely slipped the team's attention. And a huge thank you for creating this example project and amazing blog post 😄 I've now created a PR to add these: https://github.com/kedro-org/kedro-community/pull/102

**Comment by kennethleungty** [comment]
Thank you @MerelTheisenQB !
